name: MKE Check Network
on: [workflow_dispatch]

jobs:
  terraform:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-1
      TF_VERSION: 0.13.4
    name: "K8s Network Conformance Testing"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./inttest/terraform/test-cluster"
    steps:
      - name: Run git checkout
        uses: actions/checkout@v2
      - name: Print slug/short variables
        run: |
          echo "Slug variables"
          echo " - ${{ env.GITHUB_REF_SLUG }}"
          echo " - ${{ env.GITHUB_HEAD_REF_SLUG }}"
          echo " - ${{ env.GITHUB_BASE_REF_SLUG }}"
          echo " - ${{ env.GITHUB_REPOSITORY_SLUG }}"
          echo "Slug URL variables"
          echo " - ${{ env.GITHUB_REF_SLUG_URL }}"
          echo " - ${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
          echo " - ${{ env.GITHUB_BASE_REF_SLUG_URL }}"
          echo " - ${{ env.GITHUB_REPOSITORY_SLUG_URL }}"
          echo "Short SHA variables"
          echo " - ${{ env.GITHUB_SHA_SHORT }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
