name: MKE Check Network
on:
  pull_request_review_comment:
    types: [created, edited]
  workflow_dispatch:
    inputs:
      prNumber:
        description: PR against which to this workflow
        required: true
  pull_request:

jobs:
  terraform:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-1
      TF_VERSION: 0.13.4
    name: "K8s Network Conformance Testing"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./terraform/test-cluster"
    steps:
      - name: Run git checkout
        uses: actions/checkout@v2
      - name: Print slug/short variables
        run: |
          echo "Github Action variables"
          echo " - github: ${{ github }}"
          echo " - github.job: ${{ github.job }}"
          echo " - github.run_number: ${{ github.run_number }}"
          echo " - github.run_id: ${{ github.run_id }}"
          echo " - github.event_name: ${{ github.event_name }}"
          echo " - github.repository: ${{ github.repository }}"
          echo " - github.ref: ${{ github.ref }}"
          echo " - github.head_ref: ${{ github.head_ref }}"
          echo " - github.base_ref: ${{ github.base_ref }}"
          echo " - github.sha: ${{ github.sha }}"
          echo " - github.event: ${{ github.event }}"
          echo " - github.event_path: ${{ github.event_path }}"
      - name: Get PR Reference
        run: |
          PR_NUMBER=$(echo ${GITHUB_REF} | cut -d / -f 3 )
          if [ -z "$PR_NUMBER" ]; then
            echo "PR reference: refs/pull/${{ github.event.inputs.prNumber }}/merge"
          else
            echo "PR number is ${PR_NUMBER}"
          fi

