name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request_target:
    types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/users/trawler/projects/2'
        column_name: 'Needs Triage'

    - name: Assign issues and pull requests with `needs-triage` label to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'needs-triage') ||
        contains(github.event.pull_request.labels.*.name, 'needs-triage')
      with:
        project: 'https://github.com/users/trawler/projects/2'
        column_name: 'Needs Triage'
    
    - name: Assign issues and pull requests with `in-triage` label to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'in-triage') ||
        contains(github.event.pull_request.labels.*.name, 'in-triage')
      with:
        project: 'https://github.com/users/trawler/projects/2'
        column_name: 'In Triage'
    
    - name: Assign issues and pull requests with `backlog/candidate` label to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'backlog/candidate') ||
        contains(github.event.pull_request.labels.*.name, 'backlog/candidate')
      with:
        project: 'https://github.com/users/trawler/projects/2'
        column_name: 'In Triage'
        
    - name: Assign issues and pull requests with `backlog` label to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'backlog') ||
        contains(github.event.pull_request.labels.*.name, 'backlog')
      with:
        project: 'https://github.com/users/trawler/projects/2'
        column_name: 'To Do'
