name: Test Secrets in Workflow
on:
  pull_request:

jobs:
  print_secret:
    name: Get Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Get Secret from Env variables
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          if [ "$DOCKER_USERNAME" = "" ]; then
            echo "empty secret!"
            exit 1
          else
            echo "docker username = $DOCKER_USERNAME"
          fi
